# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: env-exec
    binary: env-exec
    main: ./cmd/env-exec/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  use: github-native

aurs:
  - name: env-exec-bin
    license: Apache-2.0
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/env-exec-bin.git"

brews:
  - name: env-exec
    repository:
      owner: polarn
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/polarn/env-exec"
    description: "The Environment variable executor"
    install: |
      bin.install "env-exec"
    test: |
      system "echo Sorry, no test yet"

nfpms:
  - id: env-exec
    package_name: env-exec

    formats:
      - deb
      - rpm

    vendor: polarn.net
    homepage: "https://github.com/polarn/env-exec"
    maintainer: Marcus Johansson <polarn@polarn.net>
    description: "A tool to inject environment variables from various sources (GCP Secrets Manager, GitLab) before executing commands"
    license: Apache-2.0
