name: PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  snapshot:
    name: Build Snapshot Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run GoReleaser Snapshot
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Debian Packages
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: dist/*.deb
          retention-days: 30

      - name: Upload RPM Packages
        uses: actions/upload-artifact@v4
        with:
          name: rpm-packages
          path: dist/*.rpm
          retention-days: 30

      - name: Upload Archives
        uses: actions/upload-artifact@v4
        with:
          name: archives
          path: dist/*.tar.gz
          retention-days: 30
